###Registro de usuario
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba1",
    "email": "admin@gmail.com",
    "password": "123456"
}

### login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba2",
    "email": "admin@gmail.com",
    "password": "123456"
} 

### users
Get http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluLkBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzM0Mzc3MDgzLCJleHAiOjE3MzQ0MjAyODN9.4luXhKTWeiyfORpeRsZrrLNJ2WqB-c9X0_1Wj2yILZ8
